name: flutter_super_html_viewer
description: A Flutter plugin that provides a HtmlViewer widget on multiple platforms
homepage: https://github.com/dab246/flutter_super_html_viewer.git
version: 0.0.1

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

  webview_flutter: ^3.0.0

  url_launcher: ^6.1.5

  universal_html: ^2.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true
